### ISSUE TITLE
psycopg2 fails in rawgraphs container

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-services#15]
stdout: retrieving data from simcore...,
,
stderr: Traceback (most recent call last):,
  File "/home/scu/server/input-retriever.py", line 126, in <module>,
    asyncio.get_event_loop().run_until_complete(sync_data()),
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete,
    return future.result(),
  File "/home/scu/server/input-retriever.py", line 115, in sync_data,
    await download_data(),
  File "/home/scu/server/input-retriever.py", line 58, in download_data,
    PORTS = node_ports.ports(),
  File "/usr/lib/python3.6/site-packages/simcore_sdk/node_ports/nodeports.py", line 148, in ports,
    _db_manager = dbmanager.DBManager(),
  File "/usr/lib/python3.6/site-packages/simcore_sdk/node_ports/dbmanager.py", line 67, in __init__,
    self._db_settings = DbSettings(),
  File "/usr/lib/python3.6/site-packages/simcore_sdk/node_ports/dbmanager.py", line 35, in __init__,
    self.db = create_engine(self._db_settings_config.endpoint, client_encoding='utf8'),
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine,
    return strategy.create(*args, **kwargs),
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create,
    dbapi = dialect_cls.dbapi(**dbapi_args),
  File "/usr/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 632, in dbapi,
    import psycopg2,
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>,
    from psycopg2._psycopg import (                     # noqa,
ImportError: Error loading shared library libpq.so.5: No such file or directory (needed by /usr/lib/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so),
,
Function completed with code 1.,
1 ':(',

**Comment by pcrespov** [comment]
From masu.speag.com/simcore/services/dynamic/raw-graphs:2.10.0
